apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-experiment
spec:
  selector:
    matchLabels:
      run: hpa-experiment
  replicas: 3 # Start with 3 replicas initially.
  template:
    metadata:
      labels:
        run: hpa-experiment
    spec:
      containers:
      - name: hpa-experiment
        image: k8s.gcr.io/hpa-example # Utilize example image for horizontal pod autoscaling.
        ports:
        - containerPort: 80 # Set the port to 80.
        resources:
          limits:
            cpu: 500m # Limits the container to use half of a cpu core for the application. A full core is would be cpu: 1000m where m is millicores.
          requests:
            cpu: 200m # Requests the minimum compute capacity. In this case set to 200millicores.
---
  # Service information.
apiVersion: v1
kind: Service
metadata:
  name: hpa-experiment
  labels:
    run: hpa-experiment
spec:
  ports:
  - port: 80
  selector:
    run: hpa-experiment